### ISSUE TITLE
Default config duplicates address information (sans)

### ISSUE THREAD

**Issue by chasemp** [k0sproject/k0s#618] opened 2021-01-11 15:50 UTC
**Version**
```
$ k0s version

```
> v0.8.1

**Platform**
Which platform did you run k0s on?
```
$ lsb_release -a
```

> Distributor ID:	Ubuntu
> Description:	Ubuntu 20.04.1 LTS
> Release:	20.04
> Codename:	focal

**What happened?**
Duplicate address/sans configuration within the default-config generation.

> apiVersion: [k0s.k0sproject.io/v1beta1](http://k0s.k0sproject.io/v1beta1)  
> kind: Cluster  
> metadata:  
> name: k0s  
> spec:  
> api:  
> address: 172.31.12.11  
> sans:  
> \- 172.31.12.11  
> \- 172.31.12.11

Especially in the case of linting, config auditing and cleanup this can lead to unexpected outcomes.

**How To Reproduce**

> k0s default-config

**Expected behavior**

> No duplicate/shadow parameters.

**Additional context**
Not dangerous in isolation, but for automated hygiene measures it's problematic especially.

**Comment by jnummelin** [comment] 2021-01-15 12:06
closing as duplicate of #520

**Closed by jnummelin** 2021-01-15 12:06 UTC
Labels: bug
