### ISSUE TITLE
Pod cannot communicate between adm64 and arm64 workers

### ISSUE THREAD

**Issue by lucj** [k0sproject/k0s#537] opened 2020-12-16 15:13 UTC
**Version**
```
$ k0s version
v0.8.1
```
**Platform**
Which platform did you run k0s on?
- master runs on Ubuntu 20.04
- worker 1 runs on Ubuntu 18.04
- worker 2 runs on RPI 4

**What happened?**

When deploying several Pods in the cluster, it appears that Pods running on worker1 cannot communicate with Pods running on worker2. That is totally fine if both workers runs on Ubuntu though.

**Screenshots & Logs**

```
$ export KUBECONFIG=/var/lib/k0s/pki/admin.conf
$ kubectl get no
NAME      STATUS   ROLES    AGE    VERSION
worker-1  Ready    <none>   1h23m  v1.19.4       # -> Ubuntu
worker-2  Ready    <node>   4m     v1.19.4         # -> RPI 4
```

Pods running in the cluster:
```
$ kubectl get po -o custom-columns=NAME:.metadata.name,NODE:.spec.nodeName,IP:.status.podIP
NAME           NODE       IP
whoami-5b5lx   worker-1   10.244.0.75
whoami-8lxhp   worker-2   10.244.246.2
```

Running a test Pod
```
$ kubectl run test -ti --image=alpine -- sh
```

Communication from test Pod to Pod running on worker-1 is fine.

```
/ # curl 10.244.0.75:8080
I'm whoami-5b5lx running on linux/amd64
...
```

Communication from test Pod to Pod running on worker-2 does not work.

```
/ # curl 10.244.246.2:8080
... # Hanging
```

In this example, it happens that the Pod is running on worker-1. If it was running on worker-2 that would be the same thing, it could only communicate with the Pod running on the same machine it is running on.

**Comment by jnummelin** [comment] 2020-12-16 20:30
@lucj What OS and version is your RPI4 running?

> That is totally fine if both workers runs on Ubuntu though.

Based on that I'll assume the networking on RPI4 node is busted.

First thing to always verify is that there's no firewall blocking the traffic. By default calico is running in vxlan mode so check that there's nothing blocking the vxlan UDP traffic on port 4789. One way to test the connectivity is with nmap:
```
nmap 172.17.0.5 -p 4789 -sU
```
Where the `172.17.0.5` is the nodes IP.

Check the logs of calico pods if they have any errors or other clues.

Calico also has a cli tool that can grab some diagnostics: https://github.com/projectcalico/calicoctl/releases/download/v3.16.2/calicoctl-linux-arm64
https://github.com/projectcalico/calicoctl/releases/download/v3.16.2/calicoctl-linux-amd64

Run e.g. `calicoctl node checksystem`, it checks if the needed kernel modules are present. 
(ipt_set, xt_icmp, xt_icmp6, xt_rpfilter) failing should not be alarming AFAIK, see https://github.com/projectcalico/calicoctl/issues/2204

Maybe also check that the MTU on the network is set properly. We set conservative 1450 for Calico by default, so ensure that it fits into the networks MTU. IIRC it has to be "physical network MTU size minus 50" with normal vxlan and no wireguard. See more at https://docs.projectcalico.org/networking/mtu

**Comment by lucj** [comment] 2020-12-16 20:57
Thanks @jnummelin I'll check all of this. It will be a good opportunity for me to be more familiar with Calico then 👍 
RPI runs on Rapsberry PI OS Buster ARM64 lite (beta), but had to rebuild the kernel with CONFIG_CFS_BANDWIDTH=y

**Comment by lucj** [comment] 2020-12-17 07:58
Port 4789 seems fine on RPI:
````
$ sudo nmap 192.168.1.12 -p 4789 -sU
Starting Nmap 7.91 ( https://nmap.org ) at 2020-12-17 08:43 CET
Nmap scan report for raspberrypi-3.home (192.168.1.12)
Host is up (0.0084s latency).

PORT     STATE         SERVICE
4789/udp open|filtered unknown
MAC Address: DC:A6:32:57:21:18 (Raspberry Pi Trading)

Nmap done: 1 IP address (1 host up) scanned in 0.35 seconds
````

Using calicoctl it show missing dependencies though...
 
````
pi@raspberrypi:~ $ sudo ./calicoctl node checksystem
Checking kernel version...
		5.4.83-v8+          					OK
Checking kernel modules...
		ip_set              					OK
		ip_tables           					OK
		ip6_tables          					OK
		ipt_REJECT          					OK
		ipt_rpfilter        					OK
WARNING: Unable to detect the ipt_set module as Loaded/Builtin module or lsmod
		ipt_set             					FAIL
		nf_conntrack_netlink					OK
		xt_addrtype         					OK
		xt_conntrack        					OK
WARNING: Unable to detect the xt_icmp module as Loaded/Builtin module or lsmod
		xt_icmp             					FAIL
WARNING: Unable to detect the xt_icmp6 module as Loaded/Builtin module or lsmod
		xt_icmp6            					FAIL
		xt_ipvs             					OK
		xt_mark             					OK
		xt_multiport        					OK
WARNING: Unable to detect the xt_rpfilter module as Loaded/Builtin module or lsmod
		xt_rpfilter         					FAIL
		xt_set              					OK
		xt_u32              					OK
System doesn't meet one or more minimum systems requirements to run Calico
````

**Comment by lucj** [comment] 2020-12-17 08:18
From the logs of the Calico pod running in the RPI, I cannot really tell if everything is fine though. There is an error that appears several times but only at the beginning (I guess it's during the setup phase).

````
2020-12-17 07:32:34.481 [ERROR][41] felix/route_table.go 920: Failed to get link attributes error=interface not present ifaceRegex="^vxlan.calico$" ipVersion=0x4
````

[calico.log](https://github.com/k0sproject/k0s/files/5707876/calico.log)

**Comment by lucj** [comment] 2020-12-19 21:42
I have made additional testing with a 3 workers node cluster (with default Calico configuration) on my home LAN (the master is running on DO):
- 1 is a Ubuntu box (mercury)
- the 2 other ones are RPI (the first one is running Raspberry PI OS 64 bits, the other one is running Alpine)
```
$ kubectl get no
NAME          STATUS   ROLES    AGE     VERSION
mercury       Ready    <none>   13m     v1.19.4
pi-alpine     Ready    <none>   9m29s   v1.19.4
raspberrypi   Ready    <none>   13m     v1.19.4
```
I have a test DeamonSet running in the cluster:
```
NAME           READY   STATUS    RESTARTS   AGE     IP             NODE          NOMINATED NODE   READINESS GATES
whoami-9gw4t   1/1     Running   0          6m58s   10.244.0.68    mercury       <none>           <none>
whoami-lv58v   1/1     Running   0          6m58s   10.244.13.66   pi-alpine     <none>           <none>
whoami-z8jzk   1/1     Running   0          6m58s   10.244.246.2   raspberrypi   <none>           <none>
```

I notice the network acting strangely:
- from the Ubuntu box (mercury above) I cannot communicate with the Pod running on the RPIs
- from a RPI (does not matter which one) I cannot communicate with a Pod running on the Ubuntu box
- from a RPI I can access the Pod running on the other RPI
- from each worker, I can communicate with the Pod running on this same worker

Could this be a problem related to amd64 + arm64 plugins in some ways ?

**Comment by jnummelin** [comment] 2020-12-21 16:43
The root cause turned out to be #479 , so closing this one as "duplicate"

**Closed by jnummelin** 2020-12-21 16:43 UTC
Labels: area/network, bug, question
