### ISSUE TITLE
Cannot reach pod on other node

### ISSUE THREAD

**Issue by henrikb77** [k0sproject/k0s#3024] opened 2023-04-21 11:39 UTC
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Platform

```shell
REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.1
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.1"
```

### Version

1.26.3+k0s.0

### Sysinfo

<details><summary>`k0s sysinfo`</summary>
<pre>
Total memory: 7.5 GiB (pass)
Disk space available for /var/lib/k0s: 55.7 GiB (pass)
Operating system: Linux (pass)
  Linux kernel release: 5.14.0-162.23.1.el9_1.x86_64 (pass)
  Max. file descriptors per process: current: 524288 / max: 524288 (pass)
  Executable in path: modprobe: /sbin/modprobe (pass)
  /proc file system: mounted (0x9fa0) (pass)
  Control Groups: version 2 (pass)
    cgroup controller "cpu": available (pass)
    cgroup controller "cpuacct": available (via cpu in version 2) (pass)
    cgroup controller "cpuset": available (pass)
    cgroup controller "memory": available (pass)
    cgroup controller "devices": available (assumed) (pass)
    cgroup controller "freezer": available (assumed) (pass)
    cgroup controller "pids": available (pass)
    cgroup controller "hugetlb": available (pass)
    cgroup controller "blkio": available (via io in version 2) (pass)
  CONFIG_CGROUPS: Control Group support: built-in (pass)
    CONFIG_CGROUP_FREEZER: Freezer cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_PIDS: PIDs cgroup subsystem: built-in (pass)
    CONFIG_CGROUP_DEVICE: Device controller for cgroups: built-in (pass)
    CONFIG_CPUSETS: Cpuset support: built-in (pass)
    CONFIG_CGROUP_CPUACCT: Simple CPU accounting cgroup subsystem: built-in (pass)
    CONFIG_MEMCG: Memory Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_HUGETLB: HugeTLB Resource Controller for Control Groups: built-in (pass)
    CONFIG_CGROUP_SCHED: Group CPU scheduler: built-in (pass)
      CONFIG_FAIR_GROUP_SCHED: Group scheduling for SCHED_OTHER: built-in (pass)
        CONFIG_CFS_BANDWIDTH: CPU bandwidth provisioning for FAIR_GROUP_SCHED: built-in (pass)
    CONFIG_BLK_CGROUP: Block IO controller: built-in (pass)
  CONFIG_NAMESPACES: Namespaces support: built-in (pass)
    CONFIG_UTS_NS: UTS namespace: built-in (pass)
    CONFIG_IPC_NS: IPC namespace: built-in (pass)
    CONFIG_PID_NS: PID namespace: built-in (pass)
    CONFIG_NET_NS: Network namespace: built-in (pass)
  CONFIG_NET: Networking support: built-in (pass)
    CONFIG_INET: TCP/IP networking: built-in (pass)
      CONFIG_IPV6: The IPv6 protocol: built-in (pass)
    CONFIG_NETFILTER: Network packet filtering framework (Netfilter): built-in (pass)
      CONFIG_NETFILTER_ADVANCED: Advanced netfilter configuration: built-in (pass)
      CONFIG_NETFILTER_XTABLES: Netfilter Xtables support: built-in (pass)
        CONFIG_NETFILTER_XT_TARGET_REDIRECT: REDIRECT target support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_COMMENT: "comment" match support: module (pass)
        CONFIG_NETFILTER_XT_MARK: nfmark target and match support: module (pass)
        CONFIG_NETFILTER_XT_SET: set target and match support: module (pass)
        CONFIG_NETFILTER_XT_TARGET_MASQUERADE: MASQUERADE target support: module (pass)
        CONFIG_NETFILTER_XT_NAT: "SNAT and DNAT" targets support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: "addrtype" address type match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_CONNTRACK: "conntrack" connection tracking match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_MULTIPORT: "multiport" Multiple port match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_RECENT: "recent" match support: module (pass)
        CONFIG_NETFILTER_XT_MATCH_STATISTIC: "statistic" match support: module (pass)
      CONFIG_NETFILTER_NETLINK: module (pass)
      CONFIG_NF_CONNTRACK: Netfilter connection tracking support: module (pass)
      CONFIG_NF_NAT: module (pass)
      CONFIG_IP_SET: IP set support: module (pass)
        CONFIG_IP_SET_HASH_IP: hash:ip set support: module (pass)
        CONFIG_IP_SET_HASH_NET: hash:net set support: module (pass)
      CONFIG_IP_VS: IP virtual server support: module (pass)
        CONFIG_IP_VS_NFCT: Netfilter connection tracking: built-in (pass)
      CONFIG_NF_CONNTRACK_IPV4: IPv4 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_REJECT_IPV4: IPv4 packet rejection: module (pass)
      CONFIG_NF_NAT_IPV4: IPv4 NAT: unknown (warning)
      CONFIG_IP_NF_IPTABLES: IP tables support: module (pass)
        CONFIG_IP_NF_FILTER: Packet filtering: module (pass)
          CONFIG_IP_NF_TARGET_REJECT: REJECT target support: module (pass)
        CONFIG_IP_NF_NAT: iptables NAT support: module (pass)
        CONFIG_IP_NF_MANGLE: Packet mangling: module (pass)
      CONFIG_NF_DEFRAG_IPV4: module (pass)
      CONFIG_NF_CONNTRACK_IPV6: IPv6 connetion tracking support (required for NAT): unknown (warning)
      CONFIG_NF_NAT_IPV6: IPv6 NAT: unknown (warning)
      CONFIG_IP6_NF_IPTABLES: IP6 tables support: module (pass)
        CONFIG_IP6_NF_FILTER: Packet filtering: module (pass)
        CONFIG_IP6_NF_MANGLE: Packet mangling: module (pass)
        CONFIG_IP6_NF_NAT: ip6tables NAT support: module (pass)
      CONFIG_NF_DEFRAG_IPV6: module (pass)
    CONFIG_BRIDGE: 802.1d Ethernet Bridging: module (pass)
      CONFIG_LLC: module (pass)
      CONFIG_STP: module (pass)
  CONFIG_EXT4_FS: The Extended 4 (ext4) filesystem: module (pass)
  CONFIG_PROC_FS: /proc file system support: built-in (pass)
</pre>
</details>

### What happened?

What looked like a DNS issue (very flaky behavior) now seems like a network issue. Cannot reach a pod IP on another node. Since CoreDNS depending on service load balancing may be on a different node it explains the weird DNS behavior.

### Steps to reproduce

1. Start a pod on node one, e.g. python:3.8 and run "python -m http.server 8000"
2. Start another pod and make it reside on same node as python container - curl <pod ip>:8000 works.
3. Start another pod and make it reside on other node than python container - curl <pod ip>:8000 times out
4. ping <pod ip> works in both cases, which adds to the confusion.

### Expected behavior

Curl works from pod irrespective of what node hosts it.

### Actual behavior

Curl fails if client and server pods are on different nodes.

### Additional context

Calico was chosen as CNI, no parameters set - using default Calico config.

**Comment by henrikb77** [comment] 2023-04-21 14:00
Did some further testing to narrow it down (my worker nodes are node-4 and node-5).

From a pod on node-4 I can curl a service running on node-4 or node-5 using node-ip:port

From node-4 I can curl a service in a pod on node-4 using pod-ip:port but NOT a service in a pod on node-5.

**Comment by mikhail-sakhnov** [comment] 2023-04-24 11:22
@henrikb77 it sounds like you have an issue with cross node communication, am I right? 

what environment do you run on? if it is a AWS EC2 instance, check out if the src/dst check is DISABLED. If it is some other cloud provider, check out, if they have anything like that as well.

Do your nodes have a direct connection between them, e.g. can you reach from host level from node4 to node5 and vice-verse? 

do you have selinux enabled? may it be that it prevents k0s from modifying routing table?
do you have any system level firewall (for example firewalld)? if so, than restarting the firewall might break the networking because it wipes the rules created by kube-proxy.

**Comment by henrikb77** [comment] 2023-04-24 11:35
Hi and thanks for responding @mikhail-sakhnov!

It's an on-prem VMWare setup.

firewalld was disabled on every node prior to k0s installation to make it easy (I'm in experimental phase).

Just checked, yes selinux is enabled. Although I would have expected some error message from k0sctl if it wasn't able to properly modify the routing table?

> Do your nodes have a direct connection between them, e.g. can you reach from host level from node4 to node5 and vice-verse?

Yes, there is a connection. If I start an application listening to 8000 on node-4 I can curl it from node-5. I can even curl it from a pod on node-5. But starting a similar application in a *pod* on node-4 I cannot curl it from node-5.

If the connection was completely dead I would blame VMWare/the hypervisor layer, but given the above results I feel the problem is somewhere in the Kubernetes layer.

**Comment by henrikb77** [comment] 2023-04-25 13:13
Got a pointer from a colleague who had seen similar issues on the same VMWare/RHEL setup.

Fix until next reboot:
`ethtool -K [interface] tx-checksum-ip-generic off`

Permanent fix:
`nmcli con modify [interface] ethtool.feature-tx-checksum-ip-generic off`

I've tried the first fix and curl between pods on different nodes started to work right away. Still need to do some research to understand why this is needed, whether it's OS or hypervisor causing this etc. But at least there seems to be a solution.

**Comment by juanluisvaladas** [comment] 2023-04-25 13:37
Hi @henrikb77

> ping works in both cases, which adds to the confusion.

Do you mean ping from a pod running in node A works to a pod running in node B? If so it's most likely to an MTU issue. Can you please verify the MTU following MTUs?:
1- One pod running on both node A and node B (must be equal, this value is X)
2- The NIC on both node A and node B (the value can be different, but both nodes must be X + 50 or larger)
3- What kind of network are you using in vSphere? A bridged network? Check the MTU of the vmnet or whatever you're using. Can't be smaller than the largest.

**Comment by henrikb77** [comment] 2023-04-26 06:05
@jnummelin 
This was done on the "external" interface.

@juanluisvaladas 
Found a solution/workaround above that seems unrelated to MTU. Still would like to find why I need to take that action, I'll get back if I get a better understanding.

**Comment by henrikb77** [comment] 2023-04-26 08:46
@jnummelin 
I found a less intrusive way of fixing the issue is bumping all calico images to v3.25.1.
As indicated here https://github.com/projectcalico/calico/pull/6842.

_"Reports of the kernel bug being fixed seem to have been greatly exaggerated."_

Could also help k0s users if later Calico image was used by default. From what I can see the fix has not made it into the v3.24.x track.

**Comment by jnummelin** [comment] 2023-04-26 09:02
hmm, so if I read the calico issues correctly, it's essentially a kernel bug where the checksum offloading fails and thus the packets are dropped?

> "Reports of the kernel bug being fixed seem to have been greatly exaggerated."

😂 

I believe you should be able to mitigate this also by setting new anv var for Calico: `FELIX_FEATUREDETECTOVERRIDE=ChecksumOffloadBroken=true`

In the k0s config yaml it would look like this:

```yaml
spec:
  network:
    provider: calico
    calico:
      envVars:
        FELIX_FEATUREDETECTOVERRIDE=ChecksumOffloadBroken=true
```

**Comment by henrikb77** [comment] 2023-04-26 11:54
> hmm, so if I read the calico issues correctly, it's essentially a kernel bug where the checksum offloading fails and thus the packets are dropped?
Yes, that's how I interpreted it. Searching for "tx-checksum-ip-generic + Kubernetes" shows traces of this all over the Internet.

Yes your mitigation may be safer so that I stick with same version of Calico. Just need to make a note so I remove this after k0s has moved to a later version. I'm thinking if this kernel bug finally gets fixed, Calico may re-enable offloading and it could maybe be beneficial performance-wise if it works.

Side-note: it should be 
`FELIX_FEATUREDETECTOVERRIDE: ChecksumOffloadBroken=true`

**Comment by jnummelin** [comment] 2023-04-26 18:23
> I'm thinking if this kernel bug finally gets fixed, Calico may re-enable offloading and it could maybe be beneficial performance-wise if it works.

That was one of my main concerns in the way Calico "fixes" this. I mean it feels bit overkill to disable the offloading for every single kernel when not all are affected. Yes, I get on their side it's impossible to detect which ones are affected but still.

@ncopa did some deeper investigation and it _seems_ this is fixed in upstream 5.15 kernels at least: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=linux-5.15.y&id=49677ea1513e753bd90ed1a1e2c206076b7da9ec

If/when that's going into EL kernels and to which ones, well 🤷

**Comment by henrikb77** [comment] 2023-04-27 07:31
@jnummelin Fully agree, and thanks for the input on future kernel fix!

Obviously, from my perspective this issue can be closed.

**Comment by twz123** [comment] 2023-07-07 08:28
I can reproduce this problem on kernels 5.15, 5.19, 6.1, and 6.3. In fact, I haven't come across any kernel without this problem so far. Therefore, I am reopening this issue. My suggestion is to consider including `FELIX_FEATUREDETECTOVERRIDE=ChecksumOffloadBroken=true` as the default setting for k0s 1.27.x and updating the main branch to Calico 3.25.1.

In my opinion, this change would provide a better out-of-the-box experience for users. Based on my observations, it is more likely that they are using a kernel where offloading doesn't work rather than one where it does. If users are genuinely concerned about performance and know what they're doing, they can explicitly set ChecksumOffloadBroken=false.

**Comment by jnummelin** [comment] 2023-07-17 07:52
> My suggestion is to consider including FELIX_FEATUREDETECTOVERRIDE=ChecksumOffloadBroken=true as the default setting for k0s 1.27.x

That makes sense.

**Comment by CmdrSharp** [comment] 2023-07-17 07:56
I don't think that flag is needed across all distros, is it? Currently testing Flatcar without it and all seems fine.

**Comment by juanluisvaladas** [comment] 2023-07-17 11:43
> I don't think that flag is needed across all distros, is it? Currently testing Flatcar without it and all seems fine.

I don't think it's a about the distribution, unless tx-checksum-ip-generic is disabled in flatcar by default in which case it wouldn't matter.

There are multiple factors that could influence this, for instance offloading may work on some network cards.

**Closed** 2023-07-20 11:33 UTC
Labels: bug
