### ISSUE TITLE
Metrics server has issues with konnectivity agent

### ISSUE THREAD

**Issue by dza89** [k0sproject/k0s#2068] opened 2022-08-18 19:44 UTC
### Before creating an issue, make sure you've checked the following:

- [X] You are running the latest released version of k0s
- [X] Make sure you've searched for existing issues, both open and closed
- [X] Make sure you've searched for PRs too, a fix might've been merged already
- [X] You're looking at docs for the released version, "main" branch docs are usually ahead of released versions.

### Version

v1.24.3+k0s.0

### Platform

```shell
LSB Version:    n/a
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a
```

### What happened?

Metrics server is behaving erratic, seems some issue with konnectiviy.
I've upgraded metrics server to 0.6.1 to check if that has any effect, unfortunately same issue.

### Steps to reproduce

1. k0sctl apply config:
```yaml
# k0sctl apply --config cluster.yaml
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: home-cluster
spec:
  hosts:
    - ssh:
        address: 192.168.178.7
        user: root
        port: 22
        keyPath: /home/daan/.ssh/id_rsa
      noTaints: true
      role: controller+worker
    - ssh:
        address: 192.168.178.8
        user: root
        port: 22
        keyPath: /home/daan/.ssh/id_rsa
      noTaints: true 
      role: controller+worker
```
3. Check metrics agent

### Expected behavior

A working metrics server :)

### Actual behavior

See logs

### Screenshots and logs

```
http2: server: error reading preface from client 10.244.1.44:54142: read tcp 10.244.1.45:10250->10.244.1.44:54142: read: connection reset by peer
http2: server: error reading preface from client 10.244.1.44:58076: read tcp 10.244.1.45:10250->10.244.1.44:58076: read: connection reset by peer
http2: server: error reading preface from client 10.244.0.32:46364: read tcp 10.244.1.45:10250->10.244.0.32:46364: read: connection reset by peer
http2: server: error reading preface from client 10.244.1.44:57106: read tcp 10.244.1.45:10250->10.244.1.44:57106: read: connection reset by peer
http2: server: error reading preface from client 10.244.1.44:33328: read tcp 10.244.1.45:10250->10.244.1.44:33328: read: connection reset by peer
http2: server: error reading preface from client 10.244.0.32:32872: read tcp 10.244.1.45:10250->10.244.0.32:32872: read: connection reset by peer
http2: server: error reading preface from client 10.244.1.44:35440: read tcp 10.244.1.45:10250->10.244.1.44:35440: read: connection reset by peer
http2: server: error reading preface from client 10.244.0.32:35754: read tcp 10.244.1.45:10250->10.244.0.32:35754: read: connection reset by peer
http2: server: error reading preface from client 10.244.1.44:33544: read tcp 10.244.1.45:10250->10.244.1.44:33544: read: connection reset by peer
http2: server: error reading preface from client 10.244.1.44:36082: read tcp 10.244.1.45:10250->10.244.1.44:36082: read: connection reset by peer
http2: server: error reading preface from client 10.244.1.44:38712: read tcp 10.244.1.45:10250->10.244.1.44:38712: read: connection reset by peer
```

```
konnectivity-agent-dnv69          1/1     Running   0             21m     10.244.0.31   
konnectivity-agent-j8cdk          1/1     Running   0             21m     10.244.1.37    
```

### Additional context

Did a k0s reset on both nodes before applying the yaml above.

**Comment by jnummelin** [comment] 2022-08-19 11:10
I believe this stems from the fact that there's no LB for the controlplane. As the [docs](https://docs.k0sproject.io/v1.24.3+k0s.0/high-availability/) say, for HA controlplane k0s currently **requires** an "external" LB in front.

This requirement stems from how the HA is implemented in konnectivity-agent. The agent can be configured with only single address the connect to (the LB). It then tries to "brute-force" unique connections via the LB (hence we mention also round-robin backend selection) to all controllers. k0s keeps track of how many controllers are active and re-configures the agents to tell how many unique connections they should get.

Now in your case as there's no LB (configured for k0s via `spec.api.externalAddress`) agents only connect to one of the controllers. So it's pretty much 50-50 whether or not you can get exec,logs etc. working for a given pod. Why this is seen on metrics (`kubectl top node,pod ` etc behaving irratically if I got the issue right) is because when running e.g. `kubectl top node`, the API server actually call the metrics-server's service endpoint via konnectivity tunnel.

One possible workaround in this specific case is to disable konnectivity tunneling by adding `--disable-components konnectivity-server` on the controllers systemd units. That's because konnectivity is not 100% needed when running the controller+worker role. That case kinda assumes anyways that the nodes are in a flat-ish network and API can communicate with the kubelets directly anyways.

**Comment by dza89** [comment] 2022-08-19 11:23
I saw that here as well https://github.com/k0sproject/k0s/issues/1113
But it's not clear to me what exactly is meant with HA setup, as in I'm unsure when this exact situation occurs.

Every non single-node setup is automatically considered a HA setup within k0s?
Then why isn't there an issue to solve this and is the issue above just closed?
Why isn't the lb also included in k0s?
Or why is the flag not automatically applied when this situation occurs?

So many questions :)

**Comment by jnummelin** [comment] 2022-08-19 11:48
> Every non single-node setup is automatically considered a HA setup within k0s?

No, every multi controller setup is a HA setup

> Why isn't the lb also included in k0s?

We have some effort ongoing to do that, see [this comment](https://github.com/k0sproject/k0s/issues/1150#issuecomment-1149609330) for brief description. The only decent way k0s can do it is as a "client-side" balancer on worker nodes and k0s itself does not have capabilities to create proper LB(s) (with DNS names, virtual IPs etc.) on controllers.

> Or why is the flag not automatically applied when this situation occurs?

k0s itself cannot know whether or not you are planning to add more plain worker nodes behind firewalls etc.. So k0s cannot make the call for you unfortunately on this. OR it could, but in some cases that's a wrong assumption. Hence we made a design decision that k0s is not going to try to guess that. :)

**Comment by dza89** [comment] 2022-08-19 12:04
> No, every multi controller setup is a HA setup

I would not consider two controllers a HA setup, so this wasn't completely clear to me.
Maybe change the docs from HA setup to multi controller setup? 

Rest is completely clear, thanks again.

**Comment by jnummelin** [comment] 2022-08-19 12:14
> Maybe change the docs from HA setup to multi controller setup?

That's probably good idea. Or at least we need to define what we mean by HA in this case.

**Comment by dza89** [comment] 2022-08-19 12:18
At microk8s and k3s HA equals 3 or more nodes, this is where the confusion was from my part.

**Comment by jnummelin** [comment] 2022-08-19 12:38
I guess it universal on any Kube distro which has etcd as the backend. But with k0s (and with k3s) you can have HA with 2 controllers too, assuming you use kine with some external HA Mysql (maybe some AWS RDS for example).

**Comment by cr1cr1** [comment] 2022-08-25 04:38
I also confirm that in my case, the issue was that webhooks were failing intermittently on a simple 3-node deployment on VPS.

Not just the one for the metrics-server, but I think any of them.

Side effects I have encountered:
- `kube-system/metrics-server` service was crashing intermittently with  "No agent available". Because of that, deleting namespaces would just hang.
- Trying to deploy for example `emissary-ingress` or `cert-manager` would sometimes fail because of failing calls to webhooks.

Since I *do not use an external load balancer*, the fix was indeed to add `--disable-components konnectivity-server`  to k0sctl `spec.hosts[*].installFlags`. @jnummelin explanation above made total sense.

However, the root cause is not by any means easily visible. Initially seems like a network issue, so I played around with network overlay configuration, changed OS (Debian 10 and 11, Ubuntu 20.04, 22.04), removed any firewall, and used different k0s versions. Just looking for failing webhooks in kubernetes context does not really help.

**Comment by jnummelin** [comment] 2022-08-26 07:32
> Probably metallb with internal IPs as LB for the controlplane would make sense.

That probably creates few chicken-and-egg problems setting it up. And as MetalLB works with ARP and BGP I'm not sure k0s can really rely that those are always working/enabled in different environments.

As said previously, we're cooking a fix for this in k0s by utilizing a (sort of) client side balancer for worker nodes. That would remove the need for external LBs for HA cases.

**Closed** 2022-08-29 17:47 UTC
Labels: bug

**Comment by cr1cr1** [comment] 2022-09-22 16:45
Well, using an external LB (haproxy) kind of... works: intermittently I get "duplicate server" from the `konnectivity-agent` logs on 1 or 2 out of 3 controller nodes.

Not much info out there about this.

Still not very clear to me how this connectivity agent works under a LB. Mine is set up with Round Robin, with or without persistence - kind of the same results: agent refusing to work properly while generating high CPU and huge amounts of logs.

**Comment by jsalgado78** [comment] 2023-05-29 12:42
I'm using an F5 load balancer and I get "duplicate server" from the `konnectivity-agent` logs sometimes but I can't reproduce it. 
May it be resolved upgrading apiserver-network-proxy-agent image to a newer version?

apiserver-network-proxy-agent used by k0s is 0.0.33 but Kubernetes apiserver-network-proxy latest version is 0.1.3 so it may be a apiserver-network-proxy-agent bug.

> Well, using an external LB (haproxy) kind of... works: intermittently I get "duplicate server" from the `konnectivity-agent` logs on 1 or 2 out of 3 controller nodes.
> 
> Not much info out there about this.
> 
> Still not very clear to me how this connectivity agent works under a LB. Mine is set up with Round Robin, with or without persistence - kind of the same results: agent refusing to work properly while generating high CPU and huge amounts of logs.
