### ISSUE TITLE
Multi-node controller get stuck

### ISSUE THREAD

**Issue by anibal-aguila** [k0sproject/k0s#595] opened 2021-01-01 18:08 UTC
Hi, I'm trying to setup a multi-node controller cluster and after a while (5 mins) the system turn inestable and get stuck two of three masters machines whit a konnectivity-server error.

**Version**
```
v0.9.1
```
**Platform**

```
OS:                 linux (amd64)
OS Image:           Fedora CoreOS 33.20201201.3.0
Kernel version:     5.9.11-200.fc33.x86_64
Container runtime:  containerd://1.4.3
Kubelet version:    v1.20.1-k0s1
```
**What happened?**

**Logs**

```
Jan 01 19:18:15 k0s-1 k0s[822]: time="2021-01-01 19:18:10" level=info msg="E0101 19:18:10.548256    2040 egress_selector.go:201] failed to create connection to uds name /run/k0s/konnectivity-server/konnectivity-server.sock, error: dial unix /run/k0s/konnectivity-server/konnectivity-server.sock: socket: too many open files" component=kube-apiserver
Jan 01 19:18:15 k0s-1 k0s[822]: time="2021-01-01 19:18:10" level=info msg="W0101 19:18:10.548442    2040 clientconn.go:1223] grpc: addrConn.createTransport failed to connect to {/run/k0s/konnectivity-server/konnectivity-server.sock  <nil> 0 <nil>}. Err :connection error: desc = \"transport: Error while dialing dial unix /run/k0s/konnectivity-server/konnectivity-server.sock: socket: too many open files\". Reconnecting..." component=kube-apiserver
```

**Comment by jnummelin** [comment] 2021-01-15 13:47
Closing as duplicate of #596

**Closed by jnummelin** 2021-01-15 13:47 UTC
Labels: bug
