### ISSUE TITLE
show merged config

### ISSUE THREAD

**Issue by matti** [k0sproject/k0s#1261] opened 2021-11-15 15:10 UTC
when I have partial config in `/app/config.yaml` I'd like to see the "merged config" eg. defaults plus my changes:

I'd assume from the docs that this would do it:
```
$ k0s default-config -c /app/config.yaml
```

but it only shows the default values

**Comment by kke** [comment] 2021-11-17 08:01
Something like this was also requested for k0sctl: https://github.com/k0sproject/k0sctl/issues/144

Having this would make it simple.

**Comment by jnummelin** [comment] 2021-12-21 23:04
The issue is marked as stale since no activity has been recorded in 30 days

**Comment by soider** [comment] 2021-12-27 13:51
should be fixed by #1247

**Closed** 2022-01-26 11:31 UTC
Labels: enhancement

**Comment by matti** [comment] 2022-01-26 11:50
so how do I use this, what is the k0s cli command
