### ISSUE TITLE
kubectl reports 'No resources found'

### ISSUE THREAD

**Issue by ChenQi1989** [k0sproject/k0s#530] opened 2020-12-16 07:11 UTC
**Version**
v0.8.1

**Platform**
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

**What happened?**
I tried to use `kubectl get nodes' to examine the cluster status, but got the following message.
$ kubectl get nodes
No resources found

**How To Reproduce**
sudo ./k0s server
sudo cp /var/lib/k0s/pki/admin.conf ~/admin.conf
sudo chown qichen:qichen ~/admin.conf
export KUBECONFIG=~/admin.conf
kubectl get nodes

**Expected behavior**
I would expect that the should show some information.

Process status:
$ ps -ef | grep k0s
qichen     5735  17818  0 23:09 pts/11   00:00:00 grep --color=auto k0s
root     117219 126151  0 19:10 pts/9    00:00:00 sudo ./k0s server
root     117222 117219  0 19:10 pts/9    00:00:25 ./k0s server
root     117245 117222  2 19:10 pts/9    00:07:02 /var/lib/k0s/bin/etcd --data-dir=/var/lib/k0s/etcd --listen-client-urls=https://127.0.0.1:2379 --advertise-client-urls=https://127.0.0.1:2379 --client-cert-auth=true --listen-peer-urls=https://147.11.105.171:2380 --initial-advertise-peer-urls=https://147.11.105.171:2380 --name=ala-lpggp7 --trusted-ca-file=/var/lib/k0s/pki/etcd/ca.crt --cert-file=/var/lib/k0s/pki/etcd/server.crt --key-file=/var/lib/k0s/pki/etcd/server.key --peer-trusted-ca-file=/var/lib/k0s/pki/etcd/ca.crt --peer-key-file=/var/lib/k0s/pki/etcd/peer.key --peer-cert-file=/var/lib/k0s/pki/etcd/peer.crt --log-level=info --peer-client-cert-auth=true --enable-pprof=false
root     119150 117222  8 19:10 pts/9    00:21:12 /var/lib/k0s/bin/kube-apiserver --authorization-mode=Node,RBAC --proxy-client-cert-file=/var/lib/k0s/pki/front-proxy-client.crt --service-account-key-file=/var/lib/k0s/pki/sa.pub --enable-bootstrap-token-auth=true --api-audiences=system:konnectivity-server --profiling=false --client-ca-file=/var/lib/k0s/pki/ca.crt --tls-private-key-file=/var/lib/k0s/pki/server.key --egress-selector-config-file=/var/lib/k0s/konnectivity.conf --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --requestheader-allowed-names=front-proxy-client --kubelet-client-certificate=/var/lib/k0s/pki/apiserver-kubelet-client.crt --kubelet-client-key=/var/lib/k0s/pki/apiserver-kubelet-client.key --service-account-signing-key-file=/var/lib/k0s/pki/sa.key --v=1 --service-account-issuer=api --advertise-address=147.11.105.171 --tls-cert-file=/var/lib/k0s/pki/server.crt --requestheader-group-headers=X-Remote-Group --proxy-client-key-file=/var/lib/k0s/pki/front-proxy-client.key --enable-admission-plugins=NodeRestriction --insecure-port=0 --requestheader-client-ca-file=/var/lib/k0s/pki/front-proxy-ca.crt --secure-port=6443 --allow-privileged=true --service-cluster-ip-range=10.96.0.0/12 --requestheader-username-headers=X-Remote-User --requestheader-extra-headers-prefix=X-Remote-Extra- --etcd-servers=https://127.0.0.1:2379 --etcd-cafile=/var/lib/k0s/pki/etcd/ca.crt --etcd-certfile=/var/lib/k0s/pki/apiserver-etcd-client.crt --etcd-keyfile=/var/lib/k0s/pki/apiserver-etcd-client.key
root     119151 117222  0 19:10 pts/9    00:00:02 /var/lib/k0s/bin/konnectivity-server --uds-name=/var/lib/k0s/run/konnectivity-server/konnectivity-server.sock --cluster-cert=/var/lib/k0s/pki/server.crt --cluster-key=/var/lib/k0s/pki/server.key --kubeconfig=/var/lib/k0s/pki/konnectivity.conf --mode=grpc --server-port=0 --agent-port=8132 --admin-port=8133 --agent-namespace=kube-system --agent-service-account=konnectivity-agent --authentication-audience=system:konnectivity-server --logtostderr=true --stderrthreshold=1 -v=2 --v=1 --enable-profiling=false
root     119152 117222  0 19:10 pts/9    00:01:27 /var/lib/k0s/bin/kube-scheduler --authorization-kubeconfig=/var/lib/k0s/pki/scheduler.conf --kubeconfig=/var/lib/k0s/pki/scheduler.conf --v=1 --bind-address=127.0.0.1 --leader-elect=true --profiling=false --authentication-kubeconfig=/var/lib/k0s/pki/scheduler.conf
root     119153 117222  3 19:10 pts/9    00:07:50 /var/lib/k0s/bin/kube-controller-manager --service-cluster-ip-range=10.96.0.0/12 --bind-address=127.0.0.1 --enable-hostpath-provisioner=true --authentication-kubeconfig=/var/lib/k0s/pki/ccm.conf --cluster-signing-cert-file=/var/lib/k0s/pki/ca.crt --cluster-cidr=10.244.0.0/16 --cluster-signing-key-file=/var/lib/k0s/pki/ca.key --service-account-private-key-file=/var/lib/k0s/pki/sa.key --cluster-name=k0s --controllers=*,bootstrapsigner,tokencleaner --leader-elect=true --kubeconfig=/var/lib/k0s/pki/ccm.conf --client-ca-file=/var/lib/k0s/pki/ca.crt --node-cidr-mask-size=24 --root-ca-file=/var/lib/k0s/pki/ca.crt --use-service-account-credentials=true --allocate-node-cidrs=true --authorization-kubeconfig=/var/lib/k0s/pki/ccm.conf --requestheader-client-ca-file=/var/lib/k0s/pki/front-proxy-ca.crt --profiling=false --v=1
root     119613 117222  0 19:10 pts/9    00:00:04 /home/qichen/projects/k0s/k0s api --config=/home/qichen/projects/k0s/k0s.yaml --data-dir=/var/lib/k0s

logs from k0s: (output the following lines again and again)
INFO[2020-12-15 23:10:38] I1215 23:10:38.279182  119150 client.go:360] parsed scheme: "passthrough"  component=kube-apiserver
INFO[2020-12-15 23:10:38] I1215 23:10:38.279249  119150 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://127.0.0.1:2379  <nil> 0 <nil>}] <nil> <nil>}  component=kube-apiserver
INFO[2020-12-15 23:10:38] I1215 23:10:38.279264  119150 clientconn.go:948] ClientConn switching balancer to "pick_first"  component=kube-apiserver
INFO[2020-12-15 23:10:41] current config matches existing, not gonna do anything  component=kubeproxy
INFO[2020-12-15 23:10:41] current config matches existing, not gonna do anything  component=coredns
INFO[2020-12-15 23:10:41] current config matches existing, not gonna do anything  component=calico
INFO[2020-12-15 23:10:51] current config matches existing, not gonna do anything  component=kubeproxy
INFO[2020-12-15 23:10:51] current config matches existing, not gonna do anything  component=coredns
INFO[2020-12-15 23:10:51] current config matches existing, not gonna do anything  component=calico
INFO[2020-12-15 23:11:01] current config matches existing, not gonna do anything  component=kubeproxy
INFO[2020-12-15 23:11:01] current config matches existing, not gonna do anything  component=coredns
INFO[2020-12-15 23:11:01] current config matches existing, not gonna do anything  component=calico
INFO[2020-12-15 23:11:11] current config matches existing, not gonna do anything  component=kubeproxy
INFO[2020-12-15 23:11:11] current config matches existing, not gonna do anything  component=coredns
INFO[2020-12-15 23:11:11] current config matches existing, not gonna do anything  component=calico

**Comment by ChenQi1989** [comment] 2020-12-16 07:13
To get rid of the problem in 507, I used an NA server to ensure that there is no network problem. However, the result is still not pleasant.

**Comment by ncopa** [comment] 2020-12-16 07:36
what happens if you start the server with `--enable-worker`?

**Comment by ChenQi1989** [comment] 2020-12-16 07:42
@ncopa Good! It's working.
$ kubectl get nodes
NAME         STATUS     ROLES    AGE   VERSION
ala-lpggp7   NotReady   <none>   9s    v1.19.4
$ kubectl get pod -A
NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
kube-system   calico-kube-controllers-5f6546844f-sh5p5   0/1     Pending   0          4h40m
kube-system   calico-node-xthsq                          0/1     Pending   0          100s
kube-system   coredns-5c98d7d4d8-xgxxz                   0/1     Pending   0          4h40m
kube-system   kube-proxy-6jnpj                           0/1     Pending   0          100s

**Comment by ChenQi1989** [comment] 2020-12-16 07:45
@ncopa What does '--enable-worker' mean? Is it something similar to "kubectl taint nodes --all node-role.kubernetes.io/master-"?

**Comment by ChenQi1989** [comment] 2020-12-16 07:47
The pods' status are always 'Pending'. This means that there's something wrong, right?

**Comment by ncopa** [comment] 2020-12-16 11:45
The reason why you don't see any resources on the k0s server is that we don't let the server run workloads by default.

`--enable-worker` tells the k0s server to also start up containerd and kubelet to accept workloads. So things works as designed.

https://github.com/k0sproject/k0s/blob/main/docs/FAQ.md#why-does-not-kubectl-get-nodes-show-the-server

The always 'Pending' is a separate issue. Lets close this.

**Closed by ncopa** 2020-12-16 11:45 UTC
Labels: bug

**Comment by ChenQi1989** [comment] 2020-12-17 03:27
@ncopa Thanks a lot for the info.
