### ISSUE TITLE
Cannot create a user with 0.7.0

### ISSUE THREAD

**Issue by lucj** [k0sproject/k0s#464] opened 2020-11-27 13:52 UTC
**Version**
```
$ k0s version
v0.7.0
```

**Platform**
Which platform did you run k0s on?
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.1 LTS
Release:	20.04
Codename:	focal
```

**What happened?**

Get an error message when trying to create a new user

**Screenshots & Logs**

```
ubuntu@node1:~$ k0s user create --groups "system:masters" $clusterUser > ~/clusterUser.kubeconfig
Error: unknown command "user" for "k0s"
Run 'k0s --help' for usage.
unknown command "user" for "k0s"
2020-11-27 14:08:38.543606 I | unknown command "user" for "k0s"
```

**Comment by jnummelin** [comment] 2020-11-27 13:56
duplicate of #461 

`k0s user ...` command is coming in upcoming 0.8.0 release. If you wish, there's already RC1 build available for testing, we're hoping to release it early next week.

**Closed by jnummelin** 2020-11-27 13:56 UTC
