### ISSUE TITLE
current config matches existing, not gonna do anything

### ISSUE THREAD

**Issue by ChenQi1989** [k0sproject/k0s#526] opened 2020-12-15 07:54 UTC
**Version**
v0.8.1

**Platform**
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

**What happened?**
1. wget https://github.com/k0sproject/k0s/releases/download/v0.8.1/k0s-v0.8.1-amd64
2. mv k0s-v0.8.1-amd64 k0s && chmod +x k0s
3. sudo ./k0s server

The program seemed to enter some loop, printing the output below, again and again.
"""
INFO[2020-12-15 15:46:36] I1215 15:46:36.565076   24595 client.go:360] parsed scheme: "passthrough"  component=kube-apiserver
INFO[2020-12-15 15:46:36] I1215 15:46:36.565164   24595 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{https://127.0.0.1:2379  <nil> 0 <nil>}] <nil> <nil>}  component=kube-apiserver
INFO[2020-12-15 15:46:36] I1215 15:46:36.565174   24595 clientconn.go:948] ClientConn switching balancer to "pick_first"  component=kube-apiserver
INFO[2020-12-15 15:46:44] current config matches existing, not gonna do anything  component=kubeproxy
INFO[2020-12-15 15:46:44] current config matches existing, not gonna do anything  component=calico
INFO[2020-12-15 15:46:44] current config matches existing, not gonna do anything  component=coredns
INFO[2020-12-15 15:46:54] current config matches existing, not gonna do anything  component=kubeproxy
INFO[2020-12-15 15:46:54] current config matches existing, not gonna do anything  component=calico
INFO[2020-12-15 15:46:54] current config matches existing, not gonna do anything  component=coredns
INFO[2020-12-15 15:47:04] current config matches existing, not gonna do anything  component=kubeproxy
INFO[2020-12-15 15:47:04] current config matches existing, not gonna do anything  component=calico
INFO[2020-12-15 15:47:04] current config matches existing, not gonna do anything  component=coredns
INFO[2020-12-15 15:47:14] current config matches existing, not gonna do anything  component=kubeproxy
INFO[2020-12-15 15:47:14] current config matches existing, not gonna do anything  component=calico
INFO[2020-12-15 15:47:14] current config matches existing, not gonna do anything  component=coredns
"""

**How To Reproduce**
1. wget https://github.com/k0sproject/k0s/releases/download/v0.8.1/k0s-v0.8.1-amd64
2. mv k0s-v0.8.1-amd64 k0s && chmod +x k0s
3. sudo ./k0s server

**Expected behavior**
I would expect the server starts correctly, just as stated in https://github.com/k0sproject/k0s/blob/main/docs/create-cluster.md.

**Comment by ChenQi1989** [comment] 2020-12-15 08:19
Also, does k0s require k8s to be installed?

**Comment by ChenQi1989** [comment] 2020-12-15 08:43
The output of kubectl also shows that the server is not ready.

$ kubectl get nodes
NAME            STATUS     ROLES    AGE   VERSION
pek-qchen1-d2   NotReady   <none>   21m   v1.19.4

**Comment by ChenQi1989** [comment] 2020-12-15 08:56
Update info.

I used `kubectl describe -n kube-system pod kube-proxy-65rp8', and got the following warning message.
"""
  Warning  FailedCreatePodSandBox  28m (x5 over 31m)     kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "k8s.gcr.io/pause:3.2": failed to pull image "k8s.gcr.io/pause:3.2": failed to pull and unpack image "k8s.gcr.io/pause:3.2": failed to resolve reference "k8s.gcr.io/pause:3.2": failed to do request: Head "https://k8s.gcr.io/v2/pause/manifests/3.2": dial tcp 108.177.125.82:443: i/o timeout
  Warning  FailedCreatePodSandBox  28m (x5 over 31m)     kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "k8s.gcr.io/pause:3.2": failed to pull image "k8s.gcr.io/pause:3.2": failed to pull and unpack image "k8s.gcr.io/pause:3.2": failed to resolve reference "k8s.gcr.io/pause:3.2": failed to do request: Head "https://k8s.gcr.io/v2/pause/manifests/3.2": dial tcp 108.177.125.82:443: i/o timeout
"""

However, I do have this image on my computer.

$ docker images | grep pause
k8s.gcr.io/pause                            3.2                       80d28bedfe5d        10 months ago       683kB
k8s.gcr.io/pause                            3.1                       da86e6ba6ca1        2 years ago         742kB

**Comment by jnummelin** [comment] 2020-12-15 09:12
> current config matches existing, not gonna do anything component=calico

This is just logging that calico in the cluster matches the config given at startup so there's no need to change anything. It is in `INFO` level, so no need to be alarmed on. 😄 

> does k0s require k8s to be installed?

Nope, k0s brings all kube components with it.

The pause image pull error is duplicate of #507, closing this one as the root cause is the same

**Closed by jnummelin** 2020-12-15 09:12 UTC
Labels: bug
