### ISSUE TITLE
calico couldn't be started

### ISSUE THREAD

**Issue by sacesare** [k0sproject/k0s#1397] opened 2021-12-28 18:05 UTC
### Version

v1.23.1+k0s.0

### Platform

```shell
alpine 3.15
```

### What happened?

Upon start in k0s.log :
`
time="2021-12-28 20:56:43" level=info msg="time=\"2021-12-28T20:56:43.780549257+03:00\" level=error msg=\"Failed to destroy network for sandbox \\\"346ffb3504313a49802222431a428a2104b99c47941a3b852c23e72d0758a656\\\"\" error=\"netplugin failed with no error message: fork/exec /opt/cni/bin/calico: no such file or directory\"" component=containerd
time="2021-12-28 20:56:43" level=info msg="time=\"2021-12-28T20:56:43.780872489+03:00\" level=error msg=\"RunPodSandbox for &PodSandboxMetadata{Name:whoami-deployment-85bfbd48f-r482j,Uid:b9f2e09e-15ca-4aca-a023-30974bb5718b,Namespace:default,Attempt:2,} failed, error\" error=\"failed to setup network for sandbox \\\"346ffb3504313a49802222431a428a2104b99c47941a3b852c23e72d0758a656\\\": netplugin failed with no error message: fork/exec /opt/cni/bin/calico: no such file or directory\"" component=containerd
time="2021-12-28 20:56:43" level=info msg="E1228 20:56:43.781353    3960 remote_runtime.go:209] \"RunPodSandbox from runtime service failed\" err=\"rpc error: code = Unknown desc = failed to setup network for sandbox \\\"346ffb3504313a49802222431a428a2104b99c47941a3b852c23e72d0758a656\\\": netplugin failed with no error message: fork/exec /opt/cni/bin/calico: no such file or directory\"" component=kubelet
`

but '/opt/cni/bin/calico' exist on host.
1.22 version of k0s does not have this problem.

### Steps to reproduce

Start k0s

### Actual behavior

Nothing is working because of cni unavalable.

**Comment by sacesare** [comment] 2021-12-28 19:22
It seems related to changed calico version-  3.21.2 , with 3.19.2 all ok.

**Comment by soider** [comment] 2021-12-29 10:40
@sacesare can I ask you to share the k0s.yaml config and the logs for all calico related pods?

the calico binary is uploaded to the host system by running init container for daemonset calico-node.

Is it possible to check logs for those init-containers?

Meanwhile, I try to reproduce on my own env and get back as soon as I have more understanding.

**Comment by soider** [comment] 2021-12-29 11:58
I have issue with calico cni if I first start k0s with kube-router.
Like:
- k0s controller --enable-worker
- stop it
- k0s reset
- NO machine reboot
- now new k0s controller with given config touse calico fails to start.

though reset and reboot fixes I still not sure what is the root cause.

**Comment by sacesare** [comment] 2021-12-29 19:28
@soider  no problem:
`
apiVersion: k0s.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s
spec:
  api:
    address: 10.0.43.100
    sans:
    - 10.0.43.100
    - 127.0.0.1
  extensions:
    helm:
      charts:
      - chartname: traefik/traefik
        name: traefik
        namespace: default
        version: 10.6.0
      - chartname: bitnami/metallb
        name: metallb
        namespace: default
        values: |-
          configInline:
            address-pools:
            - name: generic-cluster-pool
              protocol: layer2
              addresses:
                - x.x.x.x-y.y.y.y
        version: 2.5.9
      repositories:
      - name: traefik
        url: https://helm.traefik.io/traefik
      - name: bitnami
        url: https://charts.bitnami.com/bitnami
  network:
    provider: calico
  telemetry:
    enabled: false
`

**Comment by jnummelin** [comment] 2022-01-03 12:19
The root cause _seems_ to be the fact that Calico has changed how the CNI bins are built:
```
root@ip-172-31-34-25:~# file /opt/cni/bin/calico
/opt/cni/bin/calico: setuid ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=yFnJGaC2wGDcFn4eWNnA/xlE83szDq8R2dpNeJO5k/rW713uAGGc-9kuvfpnAW/23kHR5GrKq4fUOkZmHsL, not stripped
```
So basically it's not fully statically built anymore 😢  See https://github.com/projectcalico/calico/issues/5187

This has passed our smokes as we only check for:
- calico node pods get up and running
- calico puts all needed CNI bits into place
- node is marked ready

**Comment by twz123** [comment] 2022-04-08 06:51
Calico addressed this in projectcalico/calico#5826, which is targeted for 3.23.

> Produce both static and dynamic builds of the Calico CNI plugin, fixes compatibility with systems that do not include glibc.

**Comment by twz123** [comment] 2022-05-09 08:39
The Calico PR has been merged upstream, but no release yet. (There's the [v3.24.0-0.dev](https://github.com/projectcalico/calico/releases/tag/v3.24.0-0.dev) tag, which includes the PR, though.)

**Comment by twz123** [comment] 2022-05-10 08:50
Calico 3.23.0 is out, which contains the fix.

https://github.com/projectcalico/calico/releases/tag/v3.23.0

**Closed** 2022-05-11 10:26 UTC
Labels: bug, area/network, component/calico
