### ISSUE TITLE
k0s on alpine on rpi4 Error: Failed to create gzip reader for etcd: gzip: invalid header

### ISSUE THREAD

**Issue by symgryph** [k0sproject/k0s#782] opened 2021-03-18 02:54 UTC
**Version**
```
$ v0.11.0
```
**Platform**
Which platform did you run k0s on?
```
$ alpine 3.13.2 arm64
```
**What happened?**
when trying to run 'k0s controller' it never starts, complains about gzip header and etc not working.

**How To Reproduce**
k0s controller (using defaults)

**Expected behavior**
the controller should run. It used to a while ago with exactly the same setup.

**Screenshots & Logs**
Also add any output from kubectl if applicable:
```
INFO[2021-03-18 02:47:35] no config file given, using defaults         
INFO[2021-03-18 02:47:35] using public address: 192.168.9.54           
INFO[2021-03-18 02:47:35] using sans: [192.168.9.54]                   
INFO[2021-03-18 02:47:35] DNS address: 10.96.0.10                      
INFO[2021-03-18 02:47:35] Using storage backend etcd                   
INFO[2021-03-18 02:47:35] initializing Certificates                    
INFO[2021-03-18 02:47:35] initializing Etcd                            
INFO[2021-03-18 02:47:35] initializing APIServer                       
INFO[2021-03-18 02:47:35] initializing Konnectivity                    
INFO[2021-03-18 02:47:35] initializing Scheduler                       
INFO[2021-03-18 02:47:35] initializing Manager                         
INFO[2021-03-18 02:47:35] initializing DummyLeaderElector              
INFO[2021-03-18 02:47:35] initializing Manager                         
INFO[2021-03-18 02:47:35] initializing K0SControlAPI                   
INFO[2021-03-18 02:47:35] initializing Component                       
INFO[2021-03-18 02:47:35] initializing CSRApprover                     
INFO[2021-03-18 02:47:35] Staging /var/lib/k0s/bin/etcd                
INFO[2021-03-18 02:47:35] Staging /var/lib/k0s/bin/kube-controller-manager 
INFO[2021-03-18 02:47:35] Staging /var/lib/k0s/bin/kube-apiserver      
INFO[2021-03-18 02:47:35] Staging /var/lib/k0s/bin/konnectivity-server 
INFO[2021-03-18 02:47:35] Staging /var/lib/k0s/bin/kube-scheduler      
INFO[2021-03-18 02:47:35] kube client has been init                     component=telemetry
INFO[2021-03-18 02:47:35] segment client has been init                  component=telemetry
Error: Failed to create gzip reader for etcd: gzip: invalid header
```

**Additional context**

**Comment by ncopa** [comment] 2021-03-18 16:13
I'm pretty sure that I was able to run k0s 0.11.0 on rpi4. Maybe it got corrupted during download or something similar?

**Comment by ncopa** [comment] 2021-03-18 16:30
What is the checksum on the k0s binary?
```
$ sha256sum Downloads/k0s-v0.11.0-arm64 
af59793f9fefd45cb0aae7525450f557502d5c071f2ab439b656edb93e1fdbfa  Downloads/k0s-v0.11.0-arm64
```

**Comment by ncopa** [comment] 2021-04-08 13:07
closing because I cannot reproduce

**Closed by ncopa** 2021-04-08 13:07 UTC
Labels: bug, need more info
