### ISSUE TITLE
Make etcd configurable

### ISSUE THREAD

**Issue by simplysoft** [k0sproject/k0s#2369] opened 2022-11-08 14:27 UTC
### Is your feature request related to a problem? Please describe.

We are running k0s cluster across datacenters. K0s runs the etcd cluster with default settings which work well for local network where the average latency is low, but doesn't work well for our case (see https://etcd.io/docs/v3.5/tuning/ for more details)

### Describe the solution you would like

The etcd cluster should be configurable/customizable, either via `extraArgs` and/or by exposing some important configuration options via k0s config directly. 

In our opinion `--heartbeat-interval` and `--election-timeout` would be important enough to deserve being exposed directly as config options. 

### Describe alternatives you've considered

Using `ETCD_HEARTBEAT_INTERVAL` and `ETCD_ELECTION_TIMEOUT` to configure etcd via [environment variables](https://docs.k0sproject.io/v1.25.3+k0s.0/environment-variables/) should work, but is not that frictionless as k0s promises. 

Using that approach also has the risk that one can have conflicting configuration with what k0s does. Integrating etcd configuration options directly into the config would have the benefit that some validation could be performed.

**Comment by jnummelin** [comment] 2022-11-08 14:48
duplicate of https://github.com/k0sproject/k0s/issues/1543

**Closed** 2022-11-28 14:43 UTC
Labels: enhancement
