### ISSUE TITLE
uninstall server, worker

### ISSUE THREAD

**Issue by matti** [k0sproject/k0s#519] opened 2020-12-14 17:20 UTC
k3s has k3s-uninstall and k3s-worker-uninstall, how to completely uninstall k0s master / worker ?

**Comment by ncopa** [comment] 2020-12-15 13:04
We don't have `uninstall` currently, but would be nice to have.

**Comment by matti** [comment] 2020-12-15 14:49
would be really nice when you try out on bare metal:

![image](https://user-images.githubusercontent.com/3893/102230345-707bc000-3ef5-11eb-89e8-e78196cb5a79.png)

**Comment by trawler** [comment] 2020-12-16 15:08
I think this is the same as #278

**Comment by lucj** [comment] 2020-12-16 21:00
Waiting for the uninstall command, is there a list of cleanup commands in order to remove all the process / folders / files generated by k0s ? (/var/lib/k0s, /var/lib/kubelet, ...)

**Comment by trawler** [comment] 2021-02-05 11:08
Because we plan to merge the "uninstall" functionality into `k0s reset`, I'm closing this issue as a duplicate of #278.

**Closed by trawler** 2021-02-05 11:08 UTC
Labels: bug, enhancement, priority/P1
